# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
recipes = Recipe.create([{recipe_name: "Loaded Guacamole Tacos", recipe_description: "Mash the avocado in a medium bowl with a fork (or molcajete) until it reaches your desired consistency, chunky or smooth. Add a small squeeze each of lime and lemon juice, along with 1/4 teaspoon salt. Mix well and taste. Add more lime juice, lemon juice, and salt as you like. Stir in the remaining guacamole ingredients. (To make ahead, cover the bowl with plastic wrap and press gently against the guacamole. The entire surface of the guac should be touching and covered by the wrap, to keep air out. Then, cover the bowl with a second sheet of wrap, and refrigerate.) Add all of the black bean ingredients to a 2 quart sauce pot and heat over medium-low until hot. Turn off the heat and allow to cool to a very warm, eatable temp (a few minutes should do it). If the tortillas are not soft and pliable (or if you like your tortillas warm), stack them on a microwaveable plate, separated with paper towels, and heat for 20 to 30 seconds. Line half of each tortilla with lettuce. Spoon the black bean mixture over the lettuce (on half of the tortilla). Spoon guacamole on the other half. Top with a few shakes of hot sauce (optional) and a sprinkle of cilantro. Serve with lemon and lime wedges."}, {recipe_name: 'Green Curry', recipe_description: 'To cook the rice, bring a large pot of water to boil. Add the rinsed rice and continue boiling for 30 minutes, reducing heat as necessary to prevent overflow. Remove from heat, drain the rice and return the rice to pot. Cover and let the rice rest for 10 minutes or longer, until you’re ready to serve. Warm a large skillet with deep sides over medium heat. Once it’s hot, add a couple teaspoons of oil. Cook the onion, ginger and garlic with a sprinkle of salt for about 5 minutes, stirring often. Add the asparagus and carrots and cook for 3 more minutes, stirring occasionally. Then add the curry paste and cook, stirring often, for 2 minutes. Pour the coconut milk into the pan, along with ½ cup water and 1 ½ teaspoons sugar. Bring the mixture to a simmer. Reduce heat as necessary to maintain a gentle simmer and cook until the carrots and asparagus are tender and cooked through, about 5 to 10 minutes. Once the vegetables are done cooking, stir the spinach into the mixture and cook until the spinach has wilted, about 30 seconds. Remove the curry from heat and season with rice vinegar and soy sauce. Add salt and red pepper flakes (optional), to taste. Divide rice and curry into bowls and garnish with chopped cilantro and a sprinkle of red pepper flakes, if you’d like.'}, {recipe_name: 'Raspberry Chocolate Tart', recipe_description: "Lightly grease a 9-inch pan with a removable bottom with coconut oil.
  In a bowl, combine all of the ingredients for the crust and stir together. Press evenly into the prepared tart pan; set aside.
 Place finely chopped chocolate in a large bowl. In a small saucepan, bring coconut milk just to a boil. Pour hot coconut milk over chocolate and let stand 1 minute, then stir until smooth and creamy. Stir in raspberry preserves. Pour the filling into the prepared crust. Garnish the top with raspberries. Place tart in the refrigerator to set and cool completely, about 1-2 hours. Slice and serve. Store all leftovers in an airtight container in the refrigerator."}])
ingredients = Ingredient.create([{ingredient_name: 'fresh avocados'}, {ingredient_name: 'black beans'}, {ingredient_name: 'jalapenos'}, {ingredient_name: 'tomatoes or tomatillos'}, {ingredient_name: 'corn or small flour tortillas'}, {ingredient_name: 'corn'}, {ingredient_name: 'lime'}, {ingredient_name: 'cilantro'}, {ingredient_name: 'coconut milk'}, {ingredient_name: 'carrots'}, {ingredient_name: 'onions'}, {ingredient_name: 'garlic'}, {ingredient_name: 'green curry paste'}, {ingredient_name: 'asparagus'}, {ingredient_name: 'raspberry preserves'}, {ingredient_name: 'cocoa powder'}, {ingredient_name: 'fresh raspberries'}, {ingredient_name: 'almond flour'}])
